### ISSUE TITLE
Trivia

### ISSUE THREAD

**Issue by Wolfssouls** [bippum/listen-bot#22]
how do you create the trivia channel so purge bot can start the trivia? cause its not working on our channel

Wolfsouls - Last Tuesday at 4:46 PM
--trivia start
PurgeBOT - Last Tuesday at 4:46 PM
Try this command in the trivia channel! <#null>

**Comment by bippum** [comment]
Try turning the trivia channel off and on again: 
`--admin trivia channel none`
`--admin trivia channel <#channel>`

**Comment by Wolfssouls** [comment]
Thanks it worked

the command is a little hidden within the help menu
and is that ruby?

________________________________

**Comment by bippum** [comment]
I intended to separate the help for the commands but I can add a line for the admin part.  

The bot is written in JavaScript.

**Comment by Wolfssouls** [comment]
ah <#text> is a way of printed variables in ruby

________________________________
