### ISSUE TITLE
Issue with --lastmatch

### ISSUE THREAD

**Issue by ZainW** [bippum/listen-bot#27]
when typing
 `--lastchmatch <anything here>`

it returns the current users lastmatch instead of failing (silently? I think that's the guidline of discord bots)

**Comment by bippum** [comment]
It shouldn't fail silently actually, I was mistaken in thinking that. I'll make it so it guesses you meant `of` instead of just returning your last match.

**Comment by ZainW** [comment]
thanks :)

**Comment by bippum** [comment]
I am a bad programmer
