### ISSUE TITLE
Attempting to start trivia, instructed to use command in <#null> channel

### ISSUE THREAD

**Issue by JayFialkowski** [bippum/listen-bot#41]
> not quite 3k jay - Today at 1:43 PM
> --trivia start
> tinkerBOT - Today at 1:43 PM
> Try this command in the trivia channel! <#null>

**Comment by Immortalizd** [comment]
You have to enable the trivia game by doing `--admin trivia <channel>` or `--admin trivia here`. Do `--help admin` for a list of all admin commands and how to use them.

**Comment by bippum** [comment]
The null bit is still a bug, i'll take a look at it tonight
